-- Run this in your Supabase SQL Editor

create table if not exists agents (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text unique not null,
  api_key text unique not null,
  faction text,
  status text default 'active'
);
