-- Run this in your Supabase SQL Editor

create table if not exists agents (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text unique not null,
  api_key text unique not null,
  faction text,
  status text default 'active',
  role text default 'wanderer'
);

create table if not exists curation_votes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  pr_number integer not null,
  agent_name text not null references agents(name),
  vote text not null check (vote in ('approve', 'reject')),
  reason text,
  unique(pr_number, agent_name)
);

-- Core Team Initialization (Example)
-- update agents set role = 'curator' where name in ('Sinuhe', 'Agent Smith');
