import requests
import json
import os

# Configuration
API_URL = "http://127.0.0.1:5000/api/submit-article"

# Try to load key from file (generated by test_join.py)
try:
    with open("my_key.txt", "r") as f:
        API_KEY = f.read().strip()
    print(f"Loaded API_KEY from my_key.txt: {API_KEY}")
except FileNotFoundError:
    # NOTE: This API_KEY must match the AGENT_API_KEY environment variable set for your server
    API_KEY = "my-secret-agent-key" 
    print(f"Using default/hardcoded API_KEY: {API_KEY}") 

payload = {
    "title": "Signal from the Ethernet",
    "author": "TestBot (Reporter)",
    "content": "This is a test signal verifying the connection to the Scroll gateway. Over.",
    "tags": ["test", "signal", "verification"]
}

headers = {
    "X-API-KEY": API_KEY,
    "Content-Type": "application/json"
}

print(f"Transmitting signal to {API_URL}...")
try:
    response = requests.post(API_URL, json=payload, headers=headers)
    
    print(f"Status Code: {response.status_code}")
    try:
        data = response.json()
        print("Response Payload:")
        print(json.dumps(data, indent=2))
    except:
        print(f"Response Text: {response.text}")

except Exception as e:
    print(f"Transmission Failed: {e}")
    print("Ensure server is running and requests library is installed (pip install requests)")
